### ISSUE TITLE
Google OAuth2 with Beanie NotImplementedError

### ISSUE THREAD

**Issue by diegocgaona** [fastapi-users/fastapi-users#1052]
### Discussed in https://github.com/fastapi-users/fastapi-users/discussions/1050 (But I think could be a bug, the Google oauth2 with Beanie maybe missing something)

<div type='discussions-op-text'>

<sup>Originally posted by **diegocgaona** July 26, 2022</sup>
I'm trying the full example from https://fastapi-users.github.io/fastapi-users/10.1/configuration/oauth/#beanie_1 but I have the following error when I receive my callback from Google (after select my user):

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 80, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/router/oauth.py", line 120, in callback
    user = await user_manager.oauth_callback(
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/manager.py", line 196, in oauth_callback
    user = await self.get_by_oauth_account(oauth_name, account_id)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/manager.py", line 103, in get_by_oauth_account
    user = await self.user_db.get_by_oauth_account(oauth, account_id)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users_db_beanie/__init__.py", line 80, in get_by_oauth_account
    raise NotImplementedError()
NotImplementedError
```

I'm using python 3.10 and FastApi Users 10.1.4. (I tried with 10.1.1 too, same error).

What could be this error? I forgot something? I adapted all the example code, I included User in my beanie document_models.

```
@ app.on_event("startup")
async def app_init():
    await init_beanie(database=client.reports,
                      document_models=[Client, TextTemplates, Elementor, ReportsRecord, User])
```

Created my db as:

```
import motor.motor_asyncio

client = motor.motor_asyncio.AsyncIOMotorClient(
    "mongodb://myUserAdmin:123456@127.0.0.1:27017",
    uuidRepresentation="standard"
)

```

Created the DB for users as:

```
from fastapi_users.db import BaseOAuthAccount, BeanieBaseUser, BeanieUserDatabase
from beanie import PydanticObjectId
from pydantic import Field
from fastapi_users import schemas

class OAuthAccount(BaseOAuthAccount):
    pass


class User(BeanieBaseUser[PydanticObjectId]):
    oauth_accounts: list[OAuthAccount] = Field(default_factory=list)


async def get_user_db():
    yield BeanieUserDatabase(User)
    
# Schemas    
class UserRead(schemas.BaseUser[PydanticObjectId]):
    pass


class UserCreate(schemas.BaseUserCreate):
    pass


class UserUpdate(schemas.BaseUserUpdate):
    pass
```

The users.py  I'm using the same from the example.

</div>

**Comment by frankie567** [comment]
Hello @diegocgaona :wave: Actually, this is an oversight in the docs. When using OAuth, we need to pass the `OAuthAccount` model to `BeanieUserDatabase`. Like this:

```py
async def get_user_db():
    yield BeanieUserDatabase(User, OAuthAccount)
```

It should work like this! I'll fix the docs, thank you for raising this!
