### ISSUE TITLE
Google Oauth2 after registered first time: jwt/utils.py  force_bytes: TypeError: Expected a string value

### ISSUE THREAD

**Issue by diegocgaona** [fastapi-users/fastapi-users#1054]
## Describe the bug
After use the oauth2 login with Google (following the example on docs), the first time is OK (return on the page the access_token and token_type).
But if I try a second time (after the user is in my DB in mongoDB), I receive an Internal Server Error originated from error in `jwt/utils.py  line 22, in force_bytes`:
`TypeError: Expected a string value`
It seems that in the DB my token is changed, but there is this error.

## To Reproduce

1. Go to '[oauth_google_jwt_authorize_auth_google_authorize_get](http://localhost:8080/docs#/auth/oauth_google_jwt_authorize_auth_google_authorize_get)' and execute it.
2. Get the `authorization_url` and paste it in your browser,, then use your Google Account to login (in my case, it is a account with custom domain, not gmail).
3. After that, the browser shows: Internal Server Error
4. The error from Python is:
5. The returned error:

```
INFO:     Uvicorn running on http://localhost:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [3729] using statreload
INFO:     Started server process [3754]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:57104 - "GET /auth/google/authorize HTTP/1.1" 200 OK
INFO:     127.0.0.1:57106 - "GET /auth/google/callback?state=XXXXXXXXXX.XXXXXXX.XXXXXXXX-dyXhU&code=4/0AdQt8qhHFm_Pc05ei4fhXXXfNoVUY15pdmuVflYnKmjdWdXXXu7AKfet6cF4g&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=domain.com&prompt=none HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 80, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/router/oauth.py", line 143, in callback
    return await backend.login(strategy, user, response)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/authentication/backend.py", line 48, in login
    token = await strategy.write_token(user)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/authentication/strategy/jwt.py", line 61, in write_token
    return generate_jwt(
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/jwt.py", line 27, in generate_jwt
    return jwt.encode(payload, _get_secret_value(secret), algorithm=algorithm)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/jwt/api_jwt.py", line 64, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/jwt/api_jws.py", line 133, in encode
    key = alg_obj.prepare_key(key)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/jwt/algorithms.py", line 186, in prepare_key
    key = force_bytes(key)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/jwt/utils.py", line 22, in force_bytes
    raise TypeError("Expected a string value")
TypeError: Expected a string value

```

## Expected behavior
No errors and the access_token and token_type on the browser.

## Configuration
 - Python version :  3.10
 - FastAPI version :  0.78.0
 - FastAPI Users version : 10.1.4

### FastAPI Users configuration
They are the same from my other issue: https://github.com/fastapi-users/fastapi-users/issues/1052
Except the fix/help by @frankie567:
```
async def get_user_db():
    yield BeanieUserDatabase(User, OAuthAccount)
```

## Additional context
It seems the `key `object is not in the expected format.

**Comment by frankie567** [comment]
Reading the error stack trace, it doesn't seem related to the OAuth process. Are you sure you defined the [JWTStrategy correctly](https://fastapi-users.github.io/fastapi-users/10.1/configuration/authentication/strategies/jwt/#configuration)? What's the value of `SECRET`?

**Comment by diegocgaona** [comment]
@frankie567 , really sorry for this issue... it was a comma after my variable creation:
`SECRET = os.getenv("SECRET", ""),`
And then it was a tupple :(
