### ISSUE TITLE
Error when updating existing oauth user account

### ISSUE THREAD

**Issue by diegocgaona** [fastapi-users/fastapi-users#1184]
## Describe the bug
When I try to login with Google with an existent user, I receive `AttributeError: 'NoneType' object has no attribute 'is_active'`.
I saw that my user turns `None` in the line 227 in `/fastapi_users/manager.py`

This is where it happen:
```
        else:
            # Update oauth
            for existing_oauth_account in user.oauth_accounts:
                if (
                    existing_oauth_account.account_id == account_id
                    and existing_oauth_account.oauth_name == oauth_name
                ):
                    user = await self.user_db.update_oauth_account(
                        user, existing_oauth_account, oauth_account_dict
                    )  # HERE: This return None!

        return user
```
Before this `else` if I print my user, is everything OK, including my oauth account id, email etc.
I think that's is something `update_oauth_account()` method, but I don't really understand how it works.

## UPDATE:
After logged out and not logging in with the Google login, I tried to login with the password (the same user), but I have an error now too (it was fine before logout, I had no problem with already logged instances).
In the "normal" login, I have an error in the `fastapi_users/authentication/strategy/db/strategy.py`  in the `write_token` function:

```
    async def write_token(self, user: models.UP) -> str:
        access_token_dict = self._create_access_token_dict(user)
        access_token = await self.database.create(access_token_dict)  # HERE: It returns None
        return access_token.token
```

Here is the error for the normal login:
```
File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/router/auth.py", line 70, in login
    login_return = await backend.login(strategy, user, response)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/authentication/backend.py", line 48, in login
    token = await strategy.write_token(user)
  File "/home/diego/python/ads_report_api/.venv/lib/python3.10/site-packages/fastapi_users/authentication/strategy/db/strategy.py", line 46, in write_token
    return access_token.token
AttributeError: 'NoneType' object has no attribute 'token'
``` 

I thinks is something with the database (I'm using Beanie), I will put details bellow about it, but I don't see what is wrong, the DB is mostly following the documentation.

## To Reproduce

1. After logout from an existente account, try to login with Google or via password
2. Make the login
3. Wait for the error on the callback

## Expected behavior

My user updated in the database with the new token and my cookie saved.

## Configuration
 - Python version :3.10
 - FastAPI version : 0.95
 - FastAPI Users version : 10.4.1

### FastAPI Users configuration
I have some changes to my case, but I don't know if it affects: (I think it is not related)

```
class UserManager(ObjectIDIDMixin, BaseUserManager[User, PydanticObjectId]):
    reset_password_token_secret = SECRET
    verification_token_secret = SECRET

    async def on_after_register(self, user: User, request: Optional[Request] = None):
        print(f"User {user.id} has registered.")

    async def on_after_forgot_password(
            self, user: User, token: str, request: Optional[Request] = None
    ):
        print(f"User {user.id} has forgot their password. Reset token: {token}")

    async def on_after_request_verify(
            self, user: User, token: str, request: Optional[Request] = None
    ):
        print(f"Verification requested for user {user.id}. Verification token: {token}")

    async def on_after_login(
            self,
            user: User,
            request: Optional[Request] = None,
    ):
        global IS_OAUTH_CALLBACK
        IS_OAUTH_CALLBACK = False
        print(f"User {user.email} logged in.")

    # Changes to make Google oauth login validation for specific domains
    async def oauth_callback(
            self,
            oauth_name: str,
            access_token: str,
            account_id: str,
            account_email: str,
            expires_at: Optional[int] = None,
            refresh_token: Optional[str] = None,
            request: Optional[Request] = None,
            *,
            associate_by_email: bool = False,
            is_verified_by_default: bool = True,
            domain: Optional[str] = "mydomain.com",  # Restrict login to specific domains
    ) -> User:
        # You have here a valid access token to Google API,
        # so you can call it to get the data you need
        async with httpx.AsyncClient() as client:
            response = await client.get(
                "https://openidconnect.googleapis.com/v1/userinfo",
                headers={"Authorization": f"Bearer {access_token}"}
            )
            data = response.json()
            if domain and data.get("email_verified") and data.get("email").split('@')[1] != domain:
                raise HTTPException(detail="Invalid domain", status_code=403)
            # For security, even if not raise exception, will not validate if the domain is incorrect
            elif domain and data.get("email_verified") and data.get("email").split('@')[1] == domain:
                global IS_OAUTH_CALLBACK
                IS_OAUTH_CALLBACK = True

            return await super().oauth_callback(
                oauth_name,
                access_token,
                account_id,
                account_email,
                expires_at=expires_at,
                refresh_token=refresh_token,
                request=request,
                associate_by_email=associate_by_email,
                is_verified_by_default=is_verified_by_default,
            )

```

## More about the database config

```
from fastapi_users_db_beanie.access_token import (
    BeanieAccessTokenDatabase,
    BeanieBaseAccessToken,
)


class OAuthAccount(BaseOAuthAccount):
    pass


class User(BeanieBaseUser[PydanticObjectId]):
    oauth_accounts: list[OAuthAccount] = Field(default_factory=list)


class AccessToken(BeanieBaseAccessToken[PydanticObjectId]):
    pass


async def get_user_db():
    yield BeanieUserDatabase(User, OAuthAccount)


async def get_access_token_db():
    yield BeanieAccessTokenDatabase(AccessToken)


# Schemas    
class UserRead(schemas.BaseUser[PydanticObjectId]):
    pass


class UserCreate(schemas.BaseUserCreate):
    pass


class UserUpdate(schemas.BaseUserUpdate):
    pass
```

My strategy and transport:

```
async def get_user_manager(user_db: BeanieUserDatabase = Depends(get_user_db)):
    yield UserManager(user_db)


# Modified by me for set an extra cookie not httponly (can be checked on client side with js/react)
class MyCookieTransport(CookieTransport):
    async def get_login_response(self, token: str, response: Response) -> Any:
        response.set_cookie(
            self.cookie_name,
            token,
            max_age=self.cookie_max_age,
            path=self.cookie_path,
            domain=self.cookie_domain,
            secure=self.cookie_secure,
            httponly=self.cookie_httponly,
            samesite=self.cookie_samesite,
        )
        if IS_OAUTH_CALLBACK:
            response.status_code = status.HTTP_302_FOUND
            response.headers["Location"] = f"{FRONT_END_URL}/{FRONT_HOME_PATH}"

        # We shouldn't return directly the response
        # so that FastAPI can terminate it properly
        return None


cookie_transport = MyCookieTransport()  # cookie_max_age=3600


def get_database_strategy(
        access_token_db: AccessTokenDatabase[AccessToken] = Depends(get_access_token_db),
) -> DatabaseStrategy:
    return DatabaseStrategy(access_token_db)  # lifetime_seconds=3600


auth_backend = AuthenticationBackend(
    name="cookie",
    transport=cookie_transport,
    get_strategy=get_database_strategy,
)

fastapi_users = FastAPIUsers[User, PydanticObjectId](get_user_manager, [auth_backend])

current_active_user = fastapi_users.current_user(active=True)
```

## Additional context

Unfortunately I don't remember when it worked last time, but it was fine. I know it was at least before fast_api version 10.3.
access_token is in the beanie init

**Comment by frankie567** [comment]
Probably related to Beanie 0.18. Shall be fixed with [`fastapi-users-db-beanie==2.0.0`](https://github.com/fastapi-users/fastapi-users-db-beanie/releases/tag/v2.0.0).

**Comment by diegocgaona** [comment]
Hi @frankie567, unfortunately, after the update to [fastapi-users-db-beanie==2.0.0](https://github.com/fastapi-users/fastapi-users-db-beanie/releases/tag/v2.0.0) and last fastapi users, now I receive the error when I try to run my project:

```
Traceback (most recent call last):
  File "/home/diego/python/ads_report_api/main.py", line 15, in <module>
    from routers import clients_router, text_templates_router, elementor_router, reports_router, oauth2_tokens_router, \
  File "/home/diego/python/ads_report_api/routers/clients_router.py", line 8, in <module>
    from security.users import current_active_user
  File "/home/diego/python/ads_report_api/security/users.py", line 15, in <module>
    from database.users_db import User, get_user_db, AccessToken, get_access_token_db
  File "/home/diego/python/ads_report_api/database/users_db.py", line 16, in <module>
    class User(BeanieBaseUser[PydanticObjectId]):
TypeError: 'ModelMetaclass' object is not subscriptable
```

This is where the error occurs (it is in my database config above):
```
class User(BeanieBaseUser[PydanticObjectId]):
    oauth_accounts: list[OAuthAccount] = Field(default_factory=list)
```

**Comment by diegocgaona** [comment]
@frankie567 UPDATE:

I saw the changes in documentation now, sorry. I have to change this (declare the Document, from Beanie) to fix the error above (I didn't test the original issue yet):

```
class User(BeanieBaseUser, Document):
    oauth_accounts: list[OAuthAccount] = Field(default_factory=list)


class AccessToken(BeanieBaseAccessToken, Document):
    pass
```
